import { type GitCommit, GitCommitSchema } from './schemas';

export const gitLog: GitCommit[] = GitCommitSchema.array().parse([
  {
    hash: 'b2e6a19f4c8d3057e1a9b6c2d8f40e73a5c1908d',
    deco: '(HEAD -> main, tag: v9.0, origin/main)',
    date: 'Mon Jun 8 09:15:00 2026 -0300',
    branch: 'career/raylu',
    type: 'career',
    company: 'RAYLU_AI',
    role: 'SR SOFTWARE ENGINEER · Remote',
    body: [
      'wanted AI-native product scale; building the frontend platform',
      'for private-markets deal origination — funds representing $500B+ AUM.',
    ],
  },
  {
    hash: '7f3a2bc09f8e1d4c2b6a5d3e8c1f2a7b9d4e6c0a',
    deco: '(tag: v8.0)',
    date: 'Sat Mar 1 09:42:11 2025 +0100',
    branch: 'career/betsson',
    type: 'career',
    company: 'BETSSON_GROUP',
    role: 'SR SOFTWARE ENGINEER · Malta (EU)',
    body: [
      'wanted regulated multi-market scale; got 40M+ tx/yr',
      'across 15+ jurisdictions on a PCI-DSS payment platform.',
    ],
  },
  {
    hash: '4a9e1d886b3f2c7e0a8d5b9c1e6f4a2b3d7e8c01',
    deco: '(tag: v7.0)',
    date: 'Mon Apr 17 11:24:00 2023 -0300',
    branch: 'career/canon-medical',
    type: 'career',
    company: 'CANON_MEDICAL_SYSTEMS',
    role: 'SR SOFTWARE ENG (CONSULTING) · Remote (CA)',
    body: [
      'mission-critical hospital ops platform; full architectural',
      'ownership across multi-site network.',
    ],
  },
  {
    hash: 'cc1cc1ad202300823f5b1e8d9c4a7e2f0b6d8c1a',
    deco: '(tag: visa-ca)',
    date: 'Wed Aug 30 10:15:33 2023 -0700',
    branch: 'education/web-dev-coop',
    type: 'life',
    company: 'CICCC',
    role: 'WEB DEV CO-OP DIPLOMA · Vancouver, CA',
    body: [
      'part-time, concurrent with Canon Medical role.',
      'forcing function to relocate and earn CA work authorization.',
    ],
  },
  {
    hash: '5b6f0a4c8d9e1b3a7c2f5d8b0a4e6c9f1b3d7a02',
    deco: '(tag: v6.0)',
    date: 'Mon Dec 6 16:08:22 2021 -0300',
    branch: 'career/grupo-sbf',
    type: 'career',
    company: 'GRUPO_SBF (NIKE / CENTAURO)',
    role: 'REACT ENGINEER · São Paulo, BR (remote)',
    body: [
      'React at LATAM e-commerce scale (8M+ MAU); institutionalized',
      'experiment-driven dev (20+ A/B tests).',
    ],
  },
  {
    hash: '3d4e8c1a5b9f2c7e6d3a8b1c4e5f9d2a7b6c0e8d',
    deco: '(tag: v5.0)',
    date: 'Mon Jan 4 09:00:11 2021 -0300',
    branch: 'career/encora',
    type: 'career',
    company: 'ENCORA (DAITAN GROUP)',
    role: 'FRONTEND ENGINEER · Campinas, BR',
    body: ['enterprise B2B Angular depth; NgRx in production.'],
  },
  {
    hash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a01',
    deco: '(tag: v4.0)',
    date: 'Wed Apr 1 13:22:45 2020 -0300',
    branch: 'career/zup-itau',
    type: 'career',
    company: 'ZUP_INNOVATION (ITAÚ)',
    role: 'FRONTEND ENGINEER · Campinas, BR',
    body: [
      'first regulated / banking work; Web Components +',
      'micro-frontends across multiple banking apps.',
    ],
  },
  {
    hash: '9c8b7a6e5d4f3c2b1a0e9d8c7b6a5e4f3d2c1b0a',
    deco: '(tag: v3.0)',
    date: 'Fri Feb 1 10:30:00 2019 -0300',
    branch: 'career/venturus',
    type: 'career',
    company: 'VENTURUS',
    role: 'FULL-STACK ENGINEER (MEAN) · Campinas, BR',
    body: [
      'cut teeth on backend; -97.5% API latency (40s → <1s);',
      'Mongo → Postgres migration with custom ETL.',
    ],
  },
  {
    hash: '0e0f0a0b0c0d0e0f0a0b0c0d0e0f0a0b0c0d0e0f',
    deco: '(tag: v1.0, root-commit)',
    date: 'Mon Jun 4 08:00:00 2018 -0300',
    branch: 'career/mb-labs',
    type: 'career',
    company: 'MB_LABS',
    role: 'MOBILE / FULL STACK · Campinas, BR',
    body: [
      'first job. shipped 5-OS cross-platform from one',
      'Ionic + Angular + Electron codebase.',
    ],
    isRoot: true,
  },
]);
