import { z } from 'zod';

export const personSchema = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: 'Erik Henrique Alves Cunha',
  alternateName: 'Erik Cunha',
  jobTitle: 'Senior Full-Stack Software Engineer · Frontend Architecture & AI',
  url: 'https://erikunha.dev',
  email: 'erikhenriquealvescunha@gmail.com',
  telephone: '+5519998394086',
  knowsLanguage: [
    { '@type': 'Language', name: 'Portuguese', alternateName: 'Native' },
    { '@type': 'Language', name: 'English', alternateName: 'C1' },
    { '@type': 'Language', name: 'French', alternateName: 'A2' },
    { '@type': 'Language', name: 'Spanish', alternateName: 'B1' },
  ],
  nationality: { '@type': 'Country', name: 'Brazil' },
  address: {
    '@type': 'PostalAddress',
    addressLocality: 'Campinas',
    addressRegion: 'São Paulo',
    addressCountry: 'BR',
  },
  sameAs: ['https://linkedin.com/in/erikunha', 'https://github.com/erikunha'],
  worksFor: {
    '@type': 'Organization',
    name: 'Raylu.ai',
    url: 'https://raylu.ai',
  },
  description:
    'Full-Stack Engineer with 8+ years specializing in Applied AI systems and high-scale production architecture. Currently building the frontend platform for Raylu.ai — the AI deal-origination engine for private markets. Prior: PCI-DSS payments at Betsson Group (€1B+ ARR, 40M+ transactions/yr). Impact across e-commerce (8M+ MAU), banking (70M+ customers), and healthcare. Track record: -97.5% API latency, -98% CSS bundle, -52% TTI. Staff/Principal-track, targeting AI-forward product companies worldwide.',
  knowsAbout: [
    'LLM Engineering',
    'Retrieval-Augmented Generation (RAG)',
    'Generative AI',
    'Multi-Agent Orchestration',
    'AI Application Architecture',
    'Anthropic Claude',
    'Prompt Engineering',
    'Prompt Caching',
    'Streaming LLM Responses',
    'Function Calling',
    'Context Window Management',
    'LLM Cost Optimization',
    'AI Evaluation',
    'TypeScript',
    'TypeScript Strict Mode',
    'React 19',
    'React Server Components',
    'Next.js App Router',
    'Angular',
    'RxJS',
    'NgRx',
    'Redux',
    'StencilJS',
    'Web Components',
    'Vue.js',
    'Ionic',
    'SSR/SSG',
    'Micro-Frontend Architecture',
    'Node.js',
    'Express.js',
    'REST API Design',
    'WebSocket',
    'Python',
    'Docker',
    'AWS',
    'Amazon S3',
    'CloudFront',
    'AWS CodePipeline',
    'PostgreSQL',
    'MongoDB',
    'Redis',
    'SQL',
    'Rate Limiting Architecture',
    'Backend for Frontend (BFF)',
    'Clean Architecture',
    'Domain-Driven Design (DDD)',
    'Nx Monorepo',
    'Component-Driven Architecture',
    'PCI-DSS Systems',
    'Financial Technology',
    'Healthcare Technology',
    'Private Markets Technology',
    'B2B SaaS',
    'Banking Technology',
    'E-commerce Platforms',
    'EdTech',
    'Performance Engineering',
    'Core Web Vitals',
    'Web Accessibility (WCAG 2.1 AA)',
    'ARIA',
    'CI/CD Pipelines',
    'GitHub Actions',
    'Test-Driven Development',
    'Playwright',
    'Jest',
    'React Testing Library',
    'MSW',
    'Edge Computing',
  ],
  hasOccupation: {
    '@type': 'Occupation',
    name: 'Full-Stack Software Engineer',
    occupationLocation: { '@type': 'City', name: 'Remote / Worldwide' },
    skills:
      'TypeScript, React, Angular, Next.js, Node.js, Python, LLM Engineering, RAG, Multi-Agent Systems, PCI-DSS, AWS, Docker, Performance Engineering',
    experienceRequirements: '8+ years',
  },
  alumniOf: [
    {
      '@type': 'CollegeOrUniversity',
      name: 'Cornerstone International Community College of Canada (CICCC)',
      address: { '@type': 'PostalAddress', addressLocality: 'Vancouver', addressCountry: 'CA' },
    },
    {
      '@type': 'CollegeOrUniversity',
      name: 'Centro Universitário Salesiano de São Paulo (UNISAL)',
      address: { '@type': 'PostalAddress', addressLocality: 'Campinas', addressCountry: 'BR' },
    },
  ],
  hasCredential: [
    {
      '@type': 'EducationalOccupationalCredential',
      name: 'Angular Developer Certification',
      credentialCategory: 'certification',
      recognizedBy: {
        '@type': 'Organization',
        name: 'Alain Chautard — Google Developer Expert, Angular',
      },
    },
    {
      '@type': 'EducationalOccupationalCredential',
      name: 'Verified International Academic Qualifications',
      credentialCategory: 'certification',
      recognizedBy: { '@type': 'Organization', name: 'World Education Services (WES)' },
    },
  ],
  memberOf: {
    '@type': 'Organization',
    name: 'DevOpsDays Campinas',
    description:
      'Conference organizer — speaker sourcing, program curation, 10+ talks across DevOps, cloud, and platform engineering',
  },
  seeks: {
    '@type': 'Demand',
    itemOffered: {
      '@type': 'JobPosting',
      title: 'Senior, Staff, or Principal Engineer — Applied AI Systems & Full-Stack',
      employmentType: 'FULL_TIME',
      jobLocationType: 'TELECOMMUTE',
      description:
        'Targeting Applied AI engineering roles (Senior, Staff, or Principal IC) at AI-forward product companies. Currently based in Brazil (UTC-3), working remotely for a New York AI startup company. Open to fully remote worldwide or relocation with visa sponsorship. 8+ years across regulated industries. WES-verified credentials, English C1.',
    },
  },
} as const;

z.object({
  name: z.string().min(1),
  alternateName: z.string().min(1),
  jobTitle: z.string().min(1),
  description: z.string().min(1),
  url: z.string().url(),
  email: z.string().email(),
}).parse(personSchema);
