import path from 'node:path';

const MARKER = 'AUTO-GENERATED by scripts/sync-copilot.ts';

export function autoGenHeader(sourcePath: string): string {
  // Emit a repo-relative path so generated headers are machine-independent.
  const relative = path.isAbsolute(sourcePath)
    ? path.relative(process.cwd(), sourcePath)
    : sourcePath;
  return [
    `<!-- ${MARKER} — do not edit by hand.`,
    `     Source: ${relative}`,
    '     Regenerate with: pnpm sync:copilot -->',
  ].join('\n');
}

export function hasAutoGenHeader(content: string): boolean {
  return content.trimStart().startsWith(`<!-- ${MARKER}`);
}
