const MARKER = 'AUTO-GENERATED by scripts/sync-copilot.ts';

export function autoGenHeader(sourcePath: string): string {
  return [
    `<!-- ${MARKER} — do not edit by hand.`,
    `     Source: ${sourcePath}`,
    '     Regenerate with: pnpm sync:copilot -->',
  ].join('\n');
}

export function hasAutoGenHeader(content: string): boolean {
  return content.trimStart().startsWith(`<!-- ${MARKER}`);
}
